fix: test changes after pruning the solc optimizer
matter-labs/era-compiler-tester pull request #117
Opened 2024-10-23 08:08 UTC by hedgar2017

# What ❔

Tests the interface changes after pruning the solc optimizer.

## Checklist

- [x] PR title corresponds to the body of PR.
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

2024-10-23 19:36 UTC, sayon approved these changes

2024-10-24 09:34 UTC, antonbaliasnikov requested changes
I see `system-contracts-stable-build` pushed as an artifact. Maybe, it is pushed by mistake?

2024-10-24 15:53 UTC, hedgar2017 commented
@antonbaliasnikov not really.
We pushed it a long time ago. It can be useful for people who cannot build the system contracts locally for some reason, but still want to run and debug simpler tests.

2024-10-25 10:19 UTC, antonbaliasnikov approved these changes

2024-10-31 03:51 UTC, merged