feat: support CSV output
matter-labs/era-compiler-tester pull request #119
Opened 2024-11-06 00:29 UTC by sayon

# What ❔

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR.
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

2024-12-03 12:11 UTC, hedgar2017 requested changes
It's an amazing piece of work, thank you!
I've left a few nits.

Have you tested all major use cases manually? I'd like to produce a benchmark of our LLVM EVM BE against *solc*. Is it able to compare reports such as `Y+M3B3` with `Y+`?

2024-12-03 12:11 UTC, hedgar2017 commented on compiler_tester/src/summary/benchmark_adapters/input.rs
> +pub fn convert_input(input: InputIdentifier) -> benchmark_analyzer::Input {
Could you change these into `From`/`Into`?

2024-12-03 12:11 UTC, hedgar2017 commented on compiler_tester/src/test/context/input.rs
> +    pub case_context: &'a CaseContext<'a>,
Please add missing comments here.

2024-12-03 12:11 UTC, hedgar2017 commented on benchmark_analyzer/src/benchmark/format/csv.rs
> +                let size_str = size.map_or(String::from(""), |s| s.to_string());
Can be simplified to `size.map(|s| s.to_string()).unwrap_or_default()`?

2024-12-03 12:11 UTC, hedgar2017 commented on compiler_tester/src/compiler_tester/arguments/benchmark_format.rs
> +                "Unknown benchmark format `{}`. Supported formats: {}",
Please use `{string}` where possible!

2024-12-03 12:11 UTC, hedgar2017 commented on benchmark_analyzer/src/benchmark/mod.rs
>              .map_err(|error| anyhow::anyhow!("Benchmark file {:?} reading: {}", path, error))?;
Let's change it to `"Benchmark file {path:?} reading: {error}"`.

2024-12-03 12:11 UTC, hedgar2017 commented on compiler_tester/src/compiler_tester/arguments/mod.rs
> +    pub benchmark_format: Option<BenchmarkFormat>,
Can it be changed to an `Option`-less arg with a default?

2024-12-03 19:12 UTC, sayon commented
Fixed the comments! Let's merge when we can to minimize future conflicts.

LNT will be able to compare Y+M3B3 and Y+. But for now we can already do that using the CSV output, which is uniform regardless of the target.

For example, if I execute the following:
```
cargo run --bin compiler-tester -- --target evm --load-system-contracts system-contracts-stable-build --benchmark-format csv  -v  --benchmark  Y_evm.csv  --path tests/solidity/simple/default.sol 

cargo run --bin compiler-tester --  --target eravm  --load-system-contracts system-contracts-stable-build  -v  --benchmark-format csv --benchmark  Y.csv  --path tests/solidity/simple/default.sol
```

then I can import both files to a spreadsheet [for example to gdocs](https://docs.google.com/spreadsheets/d/19K6NI3Fpequd9X7EL7OisX-Wyvjm7CBx19loPBoL2U8/edit?gid=727563380#gid=727563380) and do basic statistics there. Once we plug in another backend to generate JSON for LNT, it can be automated.

2024-12-04 04:02 UTC, hedgar2017 requested changes

2024-12-04 04:02 UTC, hedgar2017 commented on compiler_tester/src/summary/benchmark_adapters/metadata.rs
> +pub fn convert_description(
impl From?

2024-12-04 04:02 UTC, hedgar2017 commented on compiler_tester/src/compilers/solidity/upstream/mode.rs
> +            String::from("L")
Nit: still can do early return!

2024-12-04 05:05 UTC, hedgar2017 approved these changes

2024-12-04 05:36 UTC, merged