Fix semantic tests
matter-labs/era-compiler-tester pull request #60
Opened 2024-07-02 15:17 UTC by jorbush

# What ❔

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR.
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

2024-07-11 13:51 UTC, hedgar2017 requested changes
It looks like this PR is breaking our CI for EraVM target.

Could you kindly wrap the changes with target checks?

I guess it is about some system context values, but if you're not sure, never mind. We'll look when I'm back.

2024-07-11 16:24 UTC, IAvecilla commented
> It looks like this PR is breaking our CI for EraVM target.
> 
> Could you kindly wrap the changes with target checks?
> 
> I guess it is about some system context values, but if you're not sure, never mind. We'll look when I'm back.

I figured out what was wrong. We now check the target to match with the `EVMInterpreter` before changing some storage state that the `semanticTests` expect. The CI is still failing, though.

From what I see, it is also failing in [this PR](https://github.com/matter-labs/era-compiler-tester/pull/45) with the same errors. Let me know if there's some other change needed or if those were the fixes you were referring to.

2024-07-12 20:55 UTC, hedgar2017 commented
@IAvecilla thanks!
Yeah, those failures are unrelated, as the base branch can be incomplete as well.
Let me merge this one and check there.

2024-07-12 20:55 UTC, hedgar2017 approved these changes

2024-07-12 20:56 UTC, merged