chore: update to compatibility with latest version of vm2
matter-labs/era-compiler-tester pull request #9
Opened 2024-04-10 12:15 UTC by joonazan

Had to adjust the integration a bit because of vm2 interface changes. Adjusted the amount of gas passed to the VM.

With this version vm2 only fails TransientStorage tests. Those opcodes are unimplemented.

2024-04-10 13:24 UTC, joonazan commented
Looks like vm2 will need to be public first. Also, I have realized I have to make more changes to the VM's interface to be able to integrate into core, so I think it makes sense to postpone this a bit.

2024-04-11 02:34 UTC, hedgar2017 approved these changes

2024-04-11 02:35 UTC, hedgar2017 requested changes
The tester is public now, so it can only work with public repos.
Can you FOS vm2?

2024-04-14 17:59 UTC, hedgar2017 approved these changes

2024-05-15 08:02 UTC, hedgar2017 requested changes
Could you squash your commits and force-reapply them? Unfortunately the base was changed after merging v1.5.0, and I'd like not to resolve all these conflicts manually.

2024-05-21 14:18 UTC, joonazan commented
@hedgar2017 I just removed all your commits that were not related to vm2 and the conflicts went away. This is ok because they are in main anyway, right?

2024-05-21 14:57 UTC, hedgar2017 commented
> @hedgar2017 I just removed all your commits that were not related to vm2 and the conflicts went away. This is ok because they are in main anyway, right?

Yes, I believe the history got broken is some way after merging `v1.5.0`.
Unfortunately I still can see the conflicts in this PR.

2024-05-21 16:43 UTC, hedgar2017 requested changes

2024-05-21 16:43 UTC, hedgar2017 commented on Cargo.toml
> +vm2 = {path = "../vm2"}
Probably that's why it fails.

2024-05-23 07:39 UTC, hedgar2017 approved these changes

2024-05-23 10:42 UTC, merged