feat: Pass transient storage to run_vm_multi_contracts function
matter-labs/era-compiler-tester pull request #90
Opened 2024-08-23 11:30 UTC by 0xVolosnikov

# What ❔

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR.
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

2024-08-23 11:31 UTC, hedgar2017 commented
Thanks.
Please resolve the conflicts 🫡

2024-08-23 11:35 UTC, 0xVolosnikov commented
Requires https://github.com/matter-labs/era-zkevm_tester/pull/25

2024-08-26 08:30 UTC, hedgar2017 requested changes

2024-08-26 08:30 UTC, hedgar2017 commented on compiler_tester/Cargo.toml
> +zkevm_tester = { git = "https://github.com/0xVolosnikov/era-zkevm_tester", branch = "vv-add-transient-storage-param" }
Pls change back and update this dep with `cargo update`.

2024-08-26 09:01 UTC, hedgar2017 approved these changes

2024-08-26 09:01 UTC, merged